name: Dev Build

on:
    # push:
    #     branches:
    #         - develop
    workflow_dispatch:

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry (Dev)
        uses: azure/docker-login@v1
        with:
          login-server: terraacr2025dev.azurecr.io
          username: ${{ secrets.ACR_DEV_USERNAME }}
          password: ${{ secrets.ACR_DEV_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t terraacr2025dev.azurecr.io/myapp:latest .
          docker push terraacr2025dev.azurecr.io/myapp:latest
